# Supabase Configuration File
# This file will be updated when you run: supabase link

[auth]
enabled = true

[functions.server]
verify_jwt = false

[functions.test]
verify_jwt = false

[functions.booking]
verify_jwt = false

[functions.simple]
verify_jwt = false

[functions.booking-simple]
verify_jwt = false

