/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rearknifkvcnmyszzrbv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlYXJrbmlma3Zjbm15c3p6cmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDcxNDQsImV4cCI6MjA3NTQ4MzE0NH0.5y3iFxLW9YvOUCG-Y9nBXZhzySX-9-DkDTLPymodW9s"